### PR TITLE
Add CNAME file to bind this repo with the aspinsiders.com domain

### PR DESCRIPTION
**Pull request by augustoproiete**
As per issue #11.

**Important**: Do not merge this PR before setting up the DNS entries, or we'll get an infinite redirect loop!

### CODE REVIEW

**Comment by scottcate** [comment]
Do we know who owns the domain DNS ?

**Comment by augustoproiete** [comment]
@scottcate Looks like the domain is owned by Michelle Smith which I believe is @ardalis' wife.

@ardalis Could you give us a hand?

**Comment by scottcate** [comment]
I can build a reverse proxy, and host the SSL version of this on my azure
account. I can also provide the SSL cert, if we think that's a good idea.

For example ... HTTPS:://www.eventday.com is a reverse proxy against got
hub pages.

@ScottCate

On Thursday, July 7, 2016, Caio Proiete notifications@github.com wrote:

> @scottcate https://github.com/scottcate Looks like the domain is owned
> by Michelle Smith which I believe is @ardalis https://github.com/ardalis'
> wife.
> 
> @ardalis https://github.com/ardalis Could you give us a hand?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/aspinsiders/aspinsiders.github.io/pull/12#issuecomment-231252857,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAlsch-VX3WJKFujAnr8-aeZLCFKBrPyks5qTaZ1gaJpZM4Io62v
> .

## 

@ScottCate (Mobile) 602-418-0770
Plz excuse brevity and typos.

**Review by scottdock — APPROVED** [review]
Looks good to me.

**Comment by ardalis** [comment]
I can configure DNS just let me know what is needed.

**Comment by augustoproiete** [comment]
Thanks @ardalis for setting up the DNS. Merging now.

**Pull request merged**
